### PR TITLE
NOT FOR MERGE: ETROG-3081: Add a MorphologyModelType

### PR DESCRIPTION
**Pull request by libreite**

### CODE REVIEW

**Comment by libreite** [comment]
NOT FOR MERGE - This is potentially for the December 2019 release.

**Comment by Katsuya-Tomioka** [comment]
Thanks. We'll merge this PR once decided to include for 19.12.

**Comment by Katsuya-Tomioka** [comment]
@libreite Do you need this?

**Comment by libreite** [comment]
No, I think it can be closed. ETROG-3081 was ultimately not merged.

**Comment by Katsuya-Tomioka** [comment]
Thanks. Closing.

**Pull request closed without merging**
