### PR TITLE
WS-1805 extending supported languages with licensing

### PR DESCRIPTION
**Pull request by TomHubbardBT**

### CODE REVIEW

**Comment by seth-mg** [comment]
@TomHubbardBT do you know if anything else needs to be done before this can be merged?

**Comment by TomHubbardBT** [comment]
> @TomHubbardBT do you know if anything else needs to be done before this can be merged?

Nothing I know of, it is an addition to the model, nothing changed or was deleted.

**Comment by Katsuya-Tomioka** [comment]
@TomHubbardBT can you open another PR with https://github.com/rosette-api/java/pull/160/commits/a1ffed31f714028de693b1170246ffe3bfecf246
(cherry pick the commit to master and create a new branch.)

**Comment by TomHubbardBT** [comment]
Will do.

**Comment by Katsuya-Tomioka** [comment]
The commit I mentioned already in master since March. Sorry about the confusion. Closing this PR.

**Pull request closed without merging**
