### PR TITLE
No-Jira: backout internal-release profile

### PR DESCRIPTION
**Pull request by guruxu**

### CODE REVIEW

**Review by seth-mg — COMMENTED** [review]
- Travis spat out a warning too:
  - https://travis-ci.org/rosette-api/java/jobs/258313726#L767
- pom header copyright is out of date.

**Review by seth-mg — DISMISSED** [review]

**Comment by seth-mg** [comment]
The version in the Maven example in the README is out of date too.

**Review by seth-mg — CHANGES_REQUESTED** [review]
Testing "Request changes."

**Review by seth-mg — APPROVED** [review]

**Comment by seth-mg** [comment]
@guruxu would this solve DC's problem?  Or is this PR stale?

**Comment by guruxu** [comment]
The PR is still valid, but I don't think it would magically solve his problem. This PR just moves the profile from the local pom to open-source-parent.

**Comment by seth-mg** [comment]
I think the issue is that to get the release plugin profile override to work, it must be a property.  The internal release documentation doesn't work without this PR.

**Comment by guruxu** [comment]
Can you merge once travis passes?

**Pull request merged**
