### PR TITLE
TEJ-1140: Add "modelType" option for entities.

### PR DESCRIPTION
**Pull request by c0d3d**

### CODE REVIEW

**Comment by c0d3d** [comment]
This might be the wrong branch.

**Comment by c0d3d** [comment]
I also need an internal release to consume this.

**Comment by iredpath** [comment]
needs a re-release after pulling in master

**Comment by iredpath** [comment]
@guruxu I'm not authorized, can you merge this?

**Review by iredpath — APPROVED** [review]

**Comment by seth-mg** [comment]
Travis failures are due to dependency on a temporary internal release.  Merging.

**Pull request merged**
