### PR TITLE
Rd 2101 internal release

### PR DESCRIPTION
**Pull request by iredpath**

### CODE REVIEW

**Comment by guruxu** [comment]
@iredpath there's no change in this PR other than pom version bumps?!

**Comment by iredpath** [comment]
@guruxu misunderstanding on my part.  We merged the initial pr branch (topics salience) without making an internal release first

**Comment by guruxu** [comment]
So we can close this PR w/o merging?

**Comment by iredpath** [comment]
we used up the version number, so we should still merge this to bump it on master

**Review by guruxu — APPROVED** [review]

**Pull request merged**
